name: archive-test-channels

on:
  schedule:
    - cron: "0 3 * * MON"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: node index.js
        env:
          HM_SLACK_BEARER_TOKEN: ${{ secrets.SLACK_BEARER_TOKEN }}
          HM_SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          HM_CHANNEL_REGEX: ".*test.*"
          HM_LAST_MESSAGE_MAX_AGE: "30d"
          HM_ARCHIVE_CHANNELS: "true"
          HM_SEND_MESSAGE: "true"
